2015/09/10 17:21:30 [error] [exception.CException] exception 'CException' with message 'Property "BannerController._module" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\controllers\BannerController.php(7): CComponent->__get('_module')
#1 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): BannerController->actionIndex()
#2 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\WWW\yvvy\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('')
#6 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/banner')
#7 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\WWW\yvvy\index.php(15): CApplication->run()
#9 {main}
REQUEST_URI=/index.php?r=admin/banner
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/Catalogue
---
2015/09/10 17:23:55 [error] [exception.CException] exception 'CException' with message 'Property "BannerController._module" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\controllers\BannerController.php(7): CComponent->__get('_module')
#1 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): BannerController->actionIndex()
#2 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\WWW\yvvy\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('')
#6 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/banner')
#7 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#8 D:\WWW\yvvy\index.php(15): CApplication->run()
#9 {main}
REQUEST_URI=/index.php?r=admin/banner
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/Catalogue
---
2015/09/15 10:29:51 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yvvyshop.goods' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `Goods`.
in D:\WWW\yvvy\protected\modules\admin\models\Goods.php (49)
in D:\WWW\yvvy\protected\modules\admin\views\goods\index.php (88)
in D:\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php (24)
in D:\WWW\yvvy\index.php (15)
2015/09/15 10:29:51 [error] [exception.CDbException] exception 'CDbException' with message 'The table "Goods" for active record class "Goods" cannot be found in the database.' in D:\WWW\yvvy\yii\db\ar\CActiveRecord.php:2385
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Goods))
#1 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(661): CActiveRecord->getMetaData()
#2 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(1355): CActiveRecord->getTableSchema()
#3 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#4 D:\WWW\yvvy\protected\modules\admin\models\Goods.php(49): CActiveRecord->findAll()
#5 D:\WWW\yvvy\protected\modules\admin\views\goods\index.php(88): Goods->getId()
#6 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#7 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#8 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#9 D:\WWW\yvvy\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#10 D:\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php(24): CController->render('index', Array)
#11 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): GoodsController->actionIndex()
#12 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 D:\WWW\yvvy\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('')
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/goods')
#17 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#18 D:\WWW\yvvy\index.php(15): CApplication->run()
#19 {main}
REQUEST_URI=/index.php?r=admin/goods
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/banner/update
---
2015/09/15 11:02:53 [error] [exception.CException] exception 'CException' with message 'Property "Goods.banner_group" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(145): CComponent->__get('banner_group')
#1 D:\WWW\yvvy\protected\modules\admin\views\goods\update.php(83): CActiveRecord->__get('banner_group')
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\yii\web\CController.php(782): CController->renderPartial('update', Array, true)
#6 D:\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php(54): CController->render('update', Array)
#7 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): GoodsController->actionUpdate()
#8 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 D:\WWW\yvvy\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#12 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/goods/upd...')
#13 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#14 D:\WWW\yvvy\index.php(15): CApplication->run()
#15 {main}
REQUEST_URI=/index.php?r=admin/goods/update
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/goods
---
2015/09/15 11:21:30 [error] [php] json_decode() expects parameter 1 to be string, array given (D:\WWW\yvvy\protected\modules\admin\controllers\TestController.php:9)
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\WWW\yvvy\yii\web\CController.php(286): TestController->runAction()
#2 D:\WWW\yvvy\yii\web\CController.php(265): TestController->runActionWithFilters()
#3 D:\WWW\yvvy\yii\web\CWebApplication.php(282): TestController->run()
#4 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#6 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/index.php?r=admin/test/index
in D:\WWW\yvvy\protected\modules\admin\controllers\TestController.php (9)
in D:\WWW\yvvy\index.php (15)
2015/09/15 11:44:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index?keyword=a".' in D:\WWW\yvvy\yii\web\CController.php:483
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(270): CController->missingAction('index?keyword=a')
#1 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index?keyword=a')
#2 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/test/inde...')
#3 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\WWW\yvvy\index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=admin/test/index?keyword=a
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/test/
---
2015/09/15 11:45:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index?keyword=a".' in D:\WWW\yvvy\yii\web\CController.php:483
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(270): CController->missingAction('index?keyword=a')
#1 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index?keyword=a')
#2 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/test/inde...')
#3 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\WWW\yvvy\index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=admin/test/index?keyword=a
---
2015/09/15 13:44:04 [warning] [application] Failed to set unsafe attribute "classfy_name" of "Goods".
in D:\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php (39)
in D:\WWW\yvvy\index.php (15)
2015/09/15 15:19:12 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "E:\phpStudy\WWW\yvvy\assets" is invalid. Please make sure the directory exists and is writable by the Web server process.' in E:\phpStudy\WWW\yvvy\yii\web\CAssetManager.php:138
Stack trace:
#0 E:\phpStudy\WWW\yvvy\yii\web\CAssetManager.php(123): CAssetManager->setBasePath('E:\phpStudy\WWW...')
#1 E:\phpStudy\WWW\yvvy\yii\web\CAssetManager.php(217): CAssetManager->getBasePath()
#2 E:\phpStudy\WWW\yvvy\protected\widgets\Upload\UploadWidget.php(10): CAssetManager->publish('E:\phpStudy\WWW...')
#3 E:\phpStudy\WWW\yvvy\yii\web\CBaseController.php(181): UploadWidget->run()
#4 E:\phpStudy\WWW\yvvy\protected\modules\admin\views\goods\update.php(329): CBaseController->widget('application.wid...', Array)
#5 E:\phpStudy\WWW\yvvy\yii\web\CBaseController.php(126): require('E:\phpStudy\WWW...')
#6 E:\phpStudy\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('E:\phpStudy\WWW...', Array, true)
#7 E:\phpStudy\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('E:\phpStudy\WWW...', Array, true)
#8 E:\phpStudy\WWW\yvvy\yii\web\CController.php(782): CController->renderPartial('update', Array, true)
#9 E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php(54): CController->render('update', Array)
#10 E:\phpStudy\WWW\yvvy\yii\web\actions\CInlineAction.php(49): GoodsController->actionUpdate()
#11 E:\phpStudy\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 E:\phpStudy\WWW\yvvy\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 E:\phpStudy\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#15 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/goods/upd...')
#16 E:\phpStudy\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#17 E:\phpStudy\WWW\yvvy\index.php(15): CApplication->run()
#18 {main}
REQUEST_URI=/index.php?r=admin/goods/update
HTTP_REFERER=http://yvvy.test.com/index.php?r=admin/goods
---
2015/09/15 15:23:19 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'E12123' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `Goods` (`sku_id`, `sku_name`, `spu_id`, `price`, `sku_num`, `color`, `material`, `specs`, `image`, `is_top`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9). Bound with :yp0='E12123', :yp1='测试 ', :yp2='E121212', :yp3=0, :yp4=0, :yp5='1212', :yp6='木', :yp7='1024x1024', :yp8='/uploads/images/2015-09/f2602c40f8d1711afc0ba121a1900028.jpg', :yp9=0.
in E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php (43)
in E:\phpStudy\WWW\yvvy\index.php (15)
2015/09/15 15:23:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'E12123' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `Goods` (`sku_id`, `sku_name`, `spu_id`, `price`, `sku_num`, `color`, `material`, `specs`, `image`, `is_top`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9). Bound with :yp0='E12123', :yp1='测试 ', :yp2='E121212', :yp3=0, :yp4=0, :yp5='1212', :yp6='木', :yp7='1024x1024', :yp8='/uploads/images/2015-09/f2602c40f8d1711afc0ba121a1900028.jpg', :yp9=0' in E:\phpStudy\WWW\yvvy\yii\db\CDbCommand.php:358
Stack trace:
#0 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php(43): CActiveRecord->save()
#3 E:\phpStudy\WWW\yvvy\yii\web\actions\CInlineAction.php(49): GoodsController->actionUpdate()
#4 E:\phpStudy\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 E:\phpStudy\WWW\yvvy\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 E:\phpStudy\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#8 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/goods/upd...')
#9 E:\phpStudy\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#10 E:\phpStudy\WWW\yvvy\index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=admin/goods/update
HTTP_REFERER=http://yvvy.test.com/index.php?r=admin/goods/update
---
2015/09/15 15:29:34 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'E12123' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `Goods` (`sku_id`, `sku_name`, `spu_id`, `price`, `sku_num`, `color`, `material`, `specs`, `image`, `is_top`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9). Bound with :yp0='E12123', :yp1='测试 ', :yp2='E121212', :yp3=0, :yp4=0, :yp5='1212', :yp6='木', :yp7='1024x1024', :yp8='/uploads/images/2015-09/f2602c40f8d1711afc0ba121a1900028.jpg', :yp9=0.
in E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php (44)
in E:\phpStudy\WWW\yvvy\index.php (15)
2015/09/15 15:29:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'E12123' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `Goods` (`sku_id`, `sku_name`, `spu_id`, `price`, `sku_num`, `color`, `material`, `specs`, `image`, `is_top`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9). Bound with :yp0='E12123', :yp1='测试 ', :yp2='E121212', :yp3=0, :yp4=0, :yp5='1212', :yp6='木', :yp7='1024x1024', :yp8='/uploads/images/2015-09/f2602c40f8d1711afc0ba121a1900028.jpg', :yp9=0' in E:\phpStudy\WWW\yvvy\yii\db\CDbCommand.php:358
Stack trace:
#0 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php(44): CActiveRecord->save()
#3 E:\phpStudy\WWW\yvvy\yii\web\actions\CInlineAction.php(49): GoodsController->actionUpdate()
#4 E:\phpStudy\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 E:\phpStudy\WWW\yvvy\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 E:\phpStudy\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#8 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/goods/upd...')
#9 E:\phpStudy\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#10 E:\phpStudy\WWW\yvvy\index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=admin/goods/update
HTTP_REFERER=http://yvvy.test.com/index.php?r=admin/goods/update
---
2015/09/15 15:34:06 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'E12123' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `Goods` (`sku_id`, `sku_name`, `spu_id`, `price`, `sku_num`, `color`, `material`, `specs`, `image`, `is_top`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9). Bound with :yp0='E12123', :yp1='sfds', :yp2='E121212', :yp3=0, :yp4=0, :yp5='红色', :yp6='121', :yp7='1024x1024', :yp8='', :yp9=0.
in E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php (51)
in E:\phpStudy\WWW\yvvy\index.php (15)
2015/09/15 15:34:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'E12123' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `Goods` (`sku_id`, `sku_name`, `spu_id`, `price`, `sku_num`, `color`, `material`, `specs`, `image`, `is_top`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9). Bound with :yp0='E12123', :yp1='sfds', :yp2='E121212', :yp3=0, :yp4=0, :yp5='红色', :yp6='121', :yp7='1024x1024', :yp8='', :yp9=0' in E:\phpStudy\WWW\yvvy\yii\db\CDbCommand.php:358
Stack trace:
#0 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php(51): CActiveRecord->save()
#3 E:\phpStudy\WWW\yvvy\yii\web\actions\CInlineAction.php(49): GoodsController->actionUpdate()
#4 E:\phpStudy\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 E:\phpStudy\WWW\yvvy\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 E:\phpStudy\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#8 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/goods/upd...')
#9 E:\phpStudy\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#10 E:\phpStudy\WWW\yvvy\index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=admin/goods/update
HTTP_REFERER=http://yvvy.test.com/index.php?r=admin/goods/update
---
2015/09/15 15:34:15 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'E12123' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `Goods` (`sku_id`, `sku_name`, `spu_id`, `price`, `sku_num`, `color`, `material`, `specs`, `image`, `is_top`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9). Bound with :yp0='E12123', :yp1='sfds', :yp2='E121212', :yp3=0, :yp4=0, :yp5='红色', :yp6='121', :yp7='1024x1024', :yp8='/uploads/images/2015-09/4968695648364b7fba7f8580f53d029e.jpg', :yp9=0.
in E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php (51)
in E:\phpStudy\WWW\yvvy\index.php (15)
2015/09/15 15:34:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'E12123' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `Goods` (`sku_id`, `sku_name`, `spu_id`, `price`, `sku_num`, `color`, `material`, `specs`, `image`, `is_top`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9). Bound with :yp0='E12123', :yp1='sfds', :yp2='E121212', :yp3=0, :yp4=0, :yp5='红色', :yp6='121', :yp7='1024x1024', :yp8='/uploads/images/2015-09/4968695648364b7fba7f8580f53d029e.jpg', :yp9=0' in E:\phpStudy\WWW\yvvy\yii\db\CDbCommand.php:358
Stack trace:
#0 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php(51): CActiveRecord->save()
#3 E:\phpStudy\WWW\yvvy\yii\web\actions\CInlineAction.php(49): GoodsController->actionUpdate()
#4 E:\phpStudy\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 E:\phpStudy\WWW\yvvy\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 E:\phpStudy\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#8 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/goods/upd...')
#9 E:\phpStudy\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#10 E:\phpStudy\WWW\yvvy\index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=admin/goods/update
HTTP_REFERER=http://yvvy.test.com/index.php?r=admin/goods/update
---
2015/09/15 15:35:45 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'E12123' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `Goods` (`sku_id`, `sku_name`, `spu_id`, `price`, `sku_num`, `color`, `material`, `specs`, `image`, `is_top`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9). Bound with :yp0='E12123', :yp1='sfds', :yp2='E121212', :yp3=0, :yp4=0, :yp5='红色', :yp6='121', :yp7='1024x1024', :yp8='', :yp9=0.
in E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php (54)
in E:\phpStudy\WWW\yvvy\index.php (15)
2015/09/15 15:35:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'E12123' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `Goods` (`sku_id`, `sku_name`, `spu_id`, `price`, `sku_num`, `color`, `material`, `specs`, `image`, `is_top`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9). Bound with :yp0='E12123', :yp1='sfds', :yp2='E121212', :yp3=0, :yp4=0, :yp5='红色', :yp6='121', :yp7='1024x1024', :yp8='', :yp9=0' in E:\phpStudy\WWW\yvvy\yii\db\CDbCommand.php:358
Stack trace:
#0 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php(54): CActiveRecord->save()
#3 E:\phpStudy\WWW\yvvy\yii\web\actions\CInlineAction.php(49): GoodsController->actionUpdate()
#4 E:\phpStudy\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 E:\phpStudy\WWW\yvvy\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 E:\phpStudy\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#8 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/goods/upd...')
#9 E:\phpStudy\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#10 E:\phpStudy\WWW\yvvy\index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=admin/goods/update
HTTP_REFERER=http://yvvy.test.com/index.php?r=admin/goods/update
---
2015/09/15 15:35:53 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'E12123' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `Goods` (`sku_id`, `sku_name`, `spu_id`, `price`, `sku_num`, `color`, `material`, `specs`, `image`, `is_top`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9). Bound with :yp0='E12123', :yp1='sfds', :yp2='E121212', :yp3=0, :yp4=0, :yp5='红色', :yp6='121', :yp7='1024x1024', :yp8='/uploads/images/2015-09/09510be31e77eee389e184c911e20587.jpg', :yp9=0.
in E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php (54)
in E:\phpStudy\WWW\yvvy\index.php (15)
2015/09/15 15:35:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'E12123' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `Goods` (`sku_id`, `sku_name`, `spu_id`, `price`, `sku_num`, `color`, `material`, `specs`, `image`, `is_top`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, :yp9). Bound with :yp0='E12123', :yp1='sfds', :yp2='E121212', :yp3=0, :yp4=0, :yp5='红色', :yp6='121', :yp7='1024x1024', :yp8='/uploads/images/2015-09/09510be31e77eee389e184c911e20587.jpg', :yp9=0' in E:\phpStudy\WWW\yvvy\yii\db\CDbCommand.php:358
Stack trace:
#0 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php(54): CActiveRecord->save()
#3 E:\phpStudy\WWW\yvvy\yii\web\actions\CInlineAction.php(49): GoodsController->actionUpdate()
#4 E:\phpStudy\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 E:\phpStudy\WWW\yvvy\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#6 E:\phpStudy\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#8 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/goods/upd...')
#9 E:\phpStudy\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#10 E:\phpStudy\WWW\yvvy\index.php(15): CApplication->run()
#11 {main}
REQUEST_URI=/index.php?r=admin/goods/update
HTTP_REFERER=http://yvvy.test.com/index.php?r=admin/goods/update
---
2015/09/15 15:58:40 [error] [exception.CException] exception 'CException' with message 'Property "Goods." is not defined.' in E:\phpStudy\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 E:\phpStudy\WWW\yvvy\yii\db\ar\CActiveRecord.php(145): CComponent->__get('')
#1 E:\phpStudy\WWW\yvvy\protected\modules\admin\models\Goods.php(55): CActiveRecord->__get('')
#2 E:\phpStudy\WWW\yvvy\yii\validators\CInlineValidator.php(42): Goods->checkSku('sku_id', Array)
#3 E:\phpStudy\WWW\yvvy\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(Goods), 'sku_id')
#4 E:\phpStudy\WWW\yvvy\yii\base\CModel.php(159): CValidator->validate(Object(Goods), NULL)
#5 E:\phpStudy\WWW\yvvy\protected\modules\admin\controllers\GoodsController.php(42): CModel->validate()
#6 E:\phpStudy\WWW\yvvy\yii\web\actions\CInlineAction.php(49): GoodsController->actionUpdate()
#7 E:\phpStudy\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 E:\phpStudy\WWW\yvvy\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 E:\phpStudy\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#11 E:\phpStudy\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/goods/upd...')
#12 E:\phpStudy\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#13 E:\phpStudy\WWW\yvvy\index.php(15): CApplication->run()
#14 {main}
REQUEST_URI=/index.php?r=admin/goods/update
HTTP_REFERER=http://yvvy.test.com/index.php?r=admin/goods/update
---
2015/09/15 16:29:58 [error] [exception.CException] exception 'CException' with message 'CatalogueController and its behaviors do not have a method or closure named "action".' in D:\WWW\yvvy\yii\base\CComponent.php:266
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(28): CComponent->__call('action', Array)
#1 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(28): CatalogueController->action()
#2 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#3 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#4 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#5 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#7 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#8 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#9 D:\WWW\yvvy\index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=admin/catalogue/update&id=26
---
2015/09/15 16:36:10 [error] [exception.CException] exception 'CException' with message 'Property "AdminModule.user" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\base\CModule.php(105): CComponent->__get('user')
#1 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(30): CModule->__get('user')
#2 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#3 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#4 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#5 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#7 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/ind...')
#8 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#9 D:\WWW\yvvy\index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=admin/index/index
---
2015/09/15 17:52:47 [error] [exception.CException] exception 'CException' with message 'Property "User.banner_id" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(145): CComponent->__get('banner_id')
#1 D:\WWW\yvvy\yii\base\CModel.php(596): CActiveRecord->__get('banner_id')
#2 D:\WWW\yvvy\protected\modules\admin\views\usergroup\index.php(129): CModel->offsetGet('banner_id')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#4 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#6 D:\WWW\yvvy\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#7 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(25): CController->render('index', Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionIndex()
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/index.php?r=admin/usergroup/index
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/index/index
---
2015/09/15 17:54:23 [error] [exception.CException] exception 'CException' with message 'Property "User.banner_id" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(145): CComponent->__get('banner_id')
#1 D:\WWW\yvvy\yii\base\CModel.php(596): CActiveRecord->__get('banner_id')
#2 D:\WWW\yvvy\protected\modules\admin\views\usergroup\index.php(129): CModel->offsetGet('banner_id')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#4 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#6 D:\WWW\yvvy\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#7 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(25): CController->render('index', Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionIndex()
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/index.php?r=admin/usergroup/index
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/index/index
---
2015/09/15 17:55:33 [error] [exception.CException] exception 'CException' with message 'Property "User.banner_id" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(145): CComponent->__get('banner_id')
#1 D:\WWW\yvvy\yii\base\CModel.php(596): CActiveRecord->__get('banner_id')
#2 D:\WWW\yvvy\protected\modules\admin\views\usergroup\index.php(129): CModel->offsetGet('banner_id')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#4 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#6 D:\WWW\yvvy\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#7 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(25): CController->render('index', Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionIndex()
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/index.php?r=admin/usergroup/index
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/index/index
---
2015/09/15 17:56:43 [error] [exception.CException] exception 'CException' with message 'Property "User.name" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(145): CComponent->__get('name')
#1 D:\WWW\yvvy\yii\base\CModel.php(596): CActiveRecord->__get('name')
#2 D:\WWW\yvvy\protected\modules\admin\views\usergroup\index.php(130): CModel->offsetGet('name')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#4 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#6 D:\WWW\yvvy\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#7 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(25): CController->render('index', Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionIndex()
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/index.php?r=admin/usergroup/index
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/index/index
---
2015/09/15 17:57:20 [error] [exception.CException] exception 'CException' with message 'Property "User.name" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(145): CComponent->__get('name')
#1 D:\WWW\yvvy\yii\base\CModel.php(596): CActiveRecord->__get('name')
#2 D:\WWW\yvvy\protected\modules\admin\views\usergroup\index.php(130): CModel->offsetGet('name')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#4 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#6 D:\WWW\yvvy\yii\web\CController.php(782): CController->renderPartial('index', Array, true)
#7 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(25): CController->render('index', Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionIndex()
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/index.php?r=admin/usergroup/index
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/index/index
---
2015/09/16 10:09:44 [error] [exception.CException] exception 'CException' with message 'UsergroupController cannot find the requested view "update".' in D:\WWW\yvvy\yii\web\CController.php:878
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(782): CController->renderPartial('update', Array, true)
#1 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(53): CController->render('update', Array)
#2 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionUpdate()
#3 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#6 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#7 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#9 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#12 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#13 D:\WWW\yvvy\index.php(15): CApplication->run()
#14 {main}
REQUEST_URI=/index.php?r=admin/usergroup/update
---
2015/09/16 10:42:18 [error] [php] Object of class UserGroup could not be converted to string (D:\WWW\yvvy\yii\web\helpers\CHtml.php:167)
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\views\usergroup\update.php(108): checkBoxList()
#1 D:\WWW\yvvy\yii\web\CBaseController.php(126): require()
#2 D:\WWW\yvvy\yii\web\CBaseController.php(95): UsergroupController->renderInternal()
#3 D:\WWW\yvvy\yii\web\CController.php(869): UsergroupController->renderFile()
#4 D:\WWW\yvvy\yii\web\CController.php(782): UsergroupController->renderPartial()
#5 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(51): UsergroupController->render()
#6 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionUpdate()
#7 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams()
#8 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): UsergroupController->runAction()
#9 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#10 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): UsergroupController->filterAccessAuth()
#11 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#12 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#13 D:\WWW\yvvy\yii\web\CController.php(265): UsergroupController->runActionWithFilters()
#14 D:\WWW\yvvy\yii\web\CWebApplication.php(282): UsergroupController->run()
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#16 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/index.php?r=admin/usergroup/update
in D:\WWW\yvvy\protected\modules\admin\views\usergroup\update.php (108)
in D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php (51)
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (25)
in D:\WWW\yvvy\index.php (15)
2015/09/16 14:50:41 [error] [php] json_decode() expects parameter 1 to be string, array given (D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php:30)
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): UsergroupController->runAction()
#2 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#3 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): UsergroupController->filterAccessAuth()
#4 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#6 D:\WWW\yvvy\yii\web\CController.php(265): UsergroupController->runActionWithFilters()
#7 D:\WWW\yvvy\yii\web\CWebApplication.php(282): UsergroupController->run()
#8 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#10 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/index.php?r=admin/usergroup/update
in D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php (30)
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (25)
in D:\WWW\yvvy\index.php (15)
2015/09/16 14:52:21 [error] [exception.CException] exception 'CException' with message 'Property "UserGroup.username" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:173
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(161): CComponent->__set('username', 'root')
#1 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(39): CActiveRecord->__set('username', 'root')
#2 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionUpdate()
#3 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#6 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#7 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#9 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#12 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#13 D:\WWW\yvvy\index.php(15): CApplication->run()
#14 {main}
REQUEST_URI=/index.php?r=admin/usergroup/update
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/usergroup/update
---
2015/09/16 14:53:48 [error] [exception.CException] exception 'CException' with message 'Property "UserGroup.username" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:173
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(161): CComponent->__set('username', 'root')
#1 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(39): CActiveRecord->__set('username', 'root')
#2 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionUpdate()
#3 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#6 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#7 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#9 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#12 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#13 D:\WWW\yvvy\index.php(15): CApplication->run()
#14 {main}
REQUEST_URI=/index.php?r=admin/usergroup/update
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/usergroup/update
---
2015/09/16 14:56:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/groupuser/update".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/groupuser...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=admin/groupuser/update
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/usergroup/index&Banner_page=
---
2015/09/16 15:00:07 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'root' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `user_group`) VALUES (:yp0, :yp1, :yp2). Bound with :yp0='root', :yp1='63a9f0ea7bb98050796b649e85481845', :yp2='["1"]'.
in D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php (43)
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (25)
in D:\WWW\yvvy\index.php (15)
2015/09/16 15:00:07 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'root' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `user_group`) VALUES (:yp0, :yp1, :yp2). Bound with :yp0='root', :yp1='63a9f0ea7bb98050796b649e85481845', :yp2='["1"]'' in D:\WWW\yvvy\yii\db\CDbCommand.php:358
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(43): CActiveRecord->save()
#3 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionUpdate()
#4 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#7 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#8 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#10 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#12 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#13 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#14 D:\WWW\yvvy\index.php(15): CApplication->run()
#15 {main}
REQUEST_URI=/index.php?r=admin/usergroup/update&id=1
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/usergroup/update&id=1
---
2015/09/16 15:00:13 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'root' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `user_group`) VALUES (:yp0, :yp1, :yp2). Bound with :yp0='root', :yp1='63a9f0ea7bb98050796b649e85481845', :yp2='["1"]'.
in D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php (43)
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (25)
in D:\WWW\yvvy\index.php (15)
2015/09/16 15:00:13 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'root' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `user_group`) VALUES (:yp0, :yp1, :yp2). Bound with :yp0='root', :yp1='63a9f0ea7bb98050796b649e85481845', :yp2='["1"]'' in D:\WWW\yvvy\yii\db\CDbCommand.php:358
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(43): CActiveRecord->save()
#3 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionUpdate()
#4 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#7 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#8 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#10 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#12 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#13 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#14 D:\WWW\yvvy\index.php(15): CApplication->run()
#15 {main}
REQUEST_URI=/index.php?r=admin/usergroup/update&id=1
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/usergroup/update&id=1
---
2015/09/16 15:00:33 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'root' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `user_group`) VALUES (:yp0, :yp1, :yp2). Bound with :yp0='root', :yp1='63a9f0ea7bb98050796b649e85481845', :yp2='["2","3","4","5"]'.
in D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php (43)
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (25)
in D:\WWW\yvvy\index.php (15)
2015/09/16 15:00:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'root' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `user_group`) VALUES (:yp0, :yp1, :yp2). Bound with :yp0='root', :yp1='63a9f0ea7bb98050796b649e85481845', :yp2='["2","3","4","5"]'' in D:\WWW\yvvy\yii\db\CDbCommand.php:358
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(43): CActiveRecord->save()
#3 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionUpdate()
#4 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#7 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#8 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#10 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#12 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#13 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#14 D:\WWW\yvvy\index.php(15): CApplication->run()
#15 {main}
REQUEST_URI=/index.php?r=admin/usergroup/update&id=4
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/usergroup/update&id=4
---
2015/09/16 15:01:16 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '王二小' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `user_group`) VALUES (:yp0, :yp1, :yp2). Bound with :yp0='王二小', :yp1='ea2adde5c377cb5e09d14b71935c6f32', :yp2='["1"]'.
in D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php (43)
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (25)
in D:\WWW\yvvy\index.php (15)
2015/09/16 15:01:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '王二小' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `user` (`username`, `password`, `user_group`) VALUES (:yp0, :yp1, :yp2). Bound with :yp0='王二小', :yp1='ea2adde5c377cb5e09d14b71935c6f32', :yp2='["1"]'' in D:\WWW\yvvy\yii\db\CDbCommand.php:358
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(1080): CDbCommand->execute()
#1 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(809): CActiveRecord->insert(NULL)
#2 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(43): CActiveRecord->save()
#3 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionUpdate()
#4 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#7 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#8 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#10 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#12 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#13 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#14 D:\WWW\yvvy\index.php(15): CApplication->run()
#15 {main}
REQUEST_URI=/index.php?r=admin/usergroup/update&id=8
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/usergroup/update&id=8
---
2015/09/16 15:08:41 [error] [exception.CException] exception 'CException' with message 'Property "User.usergroup" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\db\ar\CActiveRecord.php(145): CComponent->__get('usergroup')
#1 D:\WWW\yvvy\protected\modules\admin\views\usergroup\update.php(113): CActiveRecord->__get('usergroup')
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\yii\web\CController.php(782): CController->renderPartial('update', Array, true)
#6 D:\WWW\yvvy\protected\modules\admin\controllers\UsergroupController.php(54): CController->render('update', Array)
#7 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): UsergroupController->actionUpdate()
#8 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#10 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#11 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#12 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#14 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('update')
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/usergroup...')
#17 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#18 D:\WWW\yvvy\index.php(15): CApplication->run()
#19 {main}
REQUEST_URI=/index.php?r=admin/usergroup/update&id=1
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/usergroup/index&Banner_page=
---
2015/09/16 16:54:35 [error] [exception.CException] exception 'CException' with message 'IndexController and its behaviors do not have a method or closure named "displayMessage".' in D:\WWW\yvvy\yii\base\CComponent.php:266
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\views\index\login.php(124): CComponent->__call('displayMessage', Array)
#1 D:\WWW\yvvy\protected\modules\admin\views\index\login.php(124): IndexController->displayMessage()
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(33): CController->renderPartial('login', Array)
#6 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionLogin()
#7 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#10 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#11 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#13 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#16 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\WWW\yvvy\index.php(15): CApplication->run()
#18 {main}
REQUEST_URI=/index.php?r=admin/index/login
---
2015/09/16 16:57:20 [error] [exception.CException] exception 'CException' with message 'CActiveForm and its behaviors do not have a method or closure named "getErrors".' in D:\WWW\yvvy\yii\base\CComponent.php:266
Stack trace:
#0 D:\WWW\yvvy\yii\web\helpers\CHtml.php(2199): CComponent->__call('getErrors', Array)
#1 D:\WWW\yvvy\yii\web\helpers\CHtml.php(2199): CActiveForm->getErrors()
#2 D:\WWW\yvvy\yii\web\widgets\CActiveForm.php(550): CHtml::errorSummary(Object(CActiveForm), NULL, NULL, Array)
#3 D:\WWW\yvvy\protected\modules\admin\views\index\login.php(120): CActiveForm->errorSummary(Object(CActiveForm))
#4 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#5 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#6 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#7 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(33): CController->renderPartial('login', Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionLogin()
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/index.php?r=admin/index/login
---
2015/09/16 16:57:21 [error] [exception.CException] exception 'CException' with message 'CActiveForm and its behaviors do not have a method or closure named "getErrors".' in D:\WWW\yvvy\yii\base\CComponent.php:266
Stack trace:
#0 D:\WWW\yvvy\yii\web\helpers\CHtml.php(2199): CComponent->__call('getErrors', Array)
#1 D:\WWW\yvvy\yii\web\helpers\CHtml.php(2199): CActiveForm->getErrors()
#2 D:\WWW\yvvy\yii\web\widgets\CActiveForm.php(550): CHtml::errorSummary(Object(CActiveForm), NULL, NULL, Array)
#3 D:\WWW\yvvy\protected\modules\admin\views\index\login.php(120): CActiveForm->errorSummary(Object(CActiveForm))
#4 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#5 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#6 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#7 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(33): CController->renderPartial('login', Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionLogin()
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/index.php?r=admin/index/login
---
2015/09/16 17:02:31 [error] [php] Missing argument 2 for CActiveForm::error(), called in D:\WWW\yvvy\protected\modules\admin\views\index\login.php on line 108 and defined (D:\WWW\yvvy\yii\web\widgets\CActiveForm.php:444)
Stack trace:
#0 D:\WWW\yvvy\yii\web\CBaseController.php(95): IndexController->renderInternal()
#1 D:\WWW\yvvy\yii\web\CController.php(869): IndexController->renderFile()
#2 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(33): IndexController->renderPartial()
#3 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionLogin()
#4 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams()
#5 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): IndexController->runAction()
#6 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#7 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): IndexController->filterAccessAuth()
#8 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#9 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#10 D:\WWW\yvvy\yii\web\CController.php(265): IndexController->runActionWithFilters()
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(282): IndexController->run()
#12 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#13 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#14 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/index.php?r=admin/index/login
in D:\WWW\yvvy\protected\modules\admin\views\index\login.php (108)
in D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php (33)
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (25)
in D:\WWW\yvvy\index.php (15)
2015/09/16 17:03:14 [error] [exception.CException] exception 'CException' with message 'IndexController and its behaviors do not have a method or closure named "displayMessage".' in D:\WWW\yvvy\yii\base\CComponent.php:266
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\views\index\login.php(124): CComponent->__call('displayMessage', Array)
#1 D:\WWW\yvvy\protected\modules\admin\views\index\login.php(124): IndexController->displayMessage()
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(33): CController->renderPartial('login', Array)
#6 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionLogin()
#7 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#10 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#11 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#13 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#16 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\WWW\yvvy\index.php(15): CApplication->run()
#18 {main}
REQUEST_URI=/index.php?r=admin/index/login
---
2015/09/16 17:03:18 [error] [exception.CException] exception 'CException' with message 'IndexController and its behaviors do not have a method or closure named "displayMessage".' in D:\WWW\yvvy\yii\base\CComponent.php:266
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\views\index\login.php(124): CComponent->__call('displayMessage', Array)
#1 D:\WWW\yvvy\protected\modules\admin\views\index\login.php(124): IndexController->displayMessage()
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(869): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(33): CController->renderPartial('login', Array)
#6 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionLogin()
#7 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#10 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#11 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#12 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#13 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#16 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#17 D:\WWW\yvvy\index.php(15): CApplication->run()
#18 {main}
REQUEST_URI=/index.php?r=admin/index/login
---
2015/09/16 17:24:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/admin/Catalogue".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/admin/Cat...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=admin/admin/Catalogue
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/index/login
---
2015/09/16 17:24:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/admin/Catalogue".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/admin/Cat...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=admin/admin/Catalogue
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/index/login
---
2015/09/16 17:25:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/admin/Catalogue/index".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/admin/Cat...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=admin/admin/Catalogue/index
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/index/login
---
2015/09/16 17:31:13 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.user" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\components\UserIdentity.php(44): CComponent->__get('user')
#1 D:\WWW\yvvy\yii\web\auth\CWebUser.php(230): UserIdentity->getPersistentStates()
#2 D:\WWW\yvvy\protected\modules\admin\models\LoginForm.php(79): CWebUser->login(Object(UserIdentity), 0)
#3 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(27): LoginForm->login()
#4 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionLogin()
#5 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#7 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#8 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#9 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#11 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#13 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#14 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#15 D:\WWW\yvvy\index.php(15): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=admin/index/login
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/index/login
---
2015/09/16 17:31:29 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.user_group" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\components\UserIdentity.php(44): CComponent->__get('user_group')
#1 D:\WWW\yvvy\yii\web\auth\CWebUser.php(230): UserIdentity->getPersistentStates()
#2 D:\WWW\yvvy\protected\modules\admin\models\LoginForm.php(79): CWebUser->login(Object(UserIdentity), 0)
#3 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(27): LoginForm->login()
#4 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionLogin()
#5 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#7 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#8 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#9 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#11 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#13 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#14 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#15 D:\WWW\yvvy\index.php(15): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=admin/index/login
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/index/login
---
2015/09/16 17:32:17 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.user_group" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\components\UserIdentity.php(48): CComponent->__get('user_group')
#1 D:\WWW\yvvy\yii\web\auth\CWebUser.php(230): UserIdentity->getPersistentStates()
#2 D:\WWW\yvvy\protected\modules\admin\models\LoginForm.php(79): CWebUser->login(Object(UserIdentity), 0)
#3 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(27): LoginForm->login()
#4 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionLogin()
#5 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#7 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(25): CFilterChain->run()
#8 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#9 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#11 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#13 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#14 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#15 D:\WWW\yvvy\index.php(15): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=admin/index/login
HTTP_REFERER=http://yvvy.mom.com/index.php?r=admin/index/login
---
2015/09/16 17:58:31 [error] [php] strpos() expects parameter 1 to be string, array given (D:\WWW\yvvy\yii\web\CController.php:963)
Stack trace:
#0 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): CatalogueController->filterAccessAuth()
#1 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#2 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#3 D:\WWW\yvvy\yii\web\CController.php(265): CatalogueController->runActionWithFilters()
#4 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CatalogueController->run()
#5 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#6 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#7 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/index.php?r=admin/Catalogue/index
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (26)
in D:\WWW\yvvy\index.php (15)
2015/09/16 18:00:48 [error] [php] strpos() expects parameter 1 to be string, array given (D:\WWW\yvvy\yii\web\CController.php:963)
Stack trace:
#0 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): CatalogueController->filterAccessAuth()
#1 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#2 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#3 D:\WWW\yvvy\yii\web\CController.php(265): CatalogueController->runActionWithFilters()
#4 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CatalogueController->run()
#5 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#6 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#7 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/index.php?r=admin/Catalogue/index
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (26)
in D:\WWW\yvvy\index.php (15)
2015/09/17 10:25:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index/login".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('index/login')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index/login
---
2015/09/17 10:51:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "myadmin/default/index".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('myadmin/default...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/myadmin/default/index
---
2015/09/17 10:52:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "myadmin/Default/index".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('myadmin/Default...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/myadmin/Default/index.html
---
2015/09/17 10:58:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/index/login".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/index/login
---
2015/09/17 10:58:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/index/login".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/index/login
---
2015/09/17 10:58:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/index/login".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/index/login
---
2015/09/17 11:47:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/index/login".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/index/login
---
2015/09/17 11:48:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/index/login".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/index/login
---
2015/09/17 11:52:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/default".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/default')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/default/
---
2015/09/17 11:52:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/Default".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/Default')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/Default/
---
2015/09/17 12:01:37 [error] [php] is_array() expects exactly 1 parameter, 2 given (D:\WWW\yvvy\protected\modules\admin\components\Controller.php:33)
Stack trace:
#0 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#1 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#2 D:\WWW\yvvy\yii\web\CController.php(265): CatalogueController->runActionWithFilters()
#3 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CatalogueController->run()
#4 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#6 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/admin/catalogue/index
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (33)
in D:\WWW\yvvy\index.php (15)
2015/09/17 12:02:49 [error] [php] is_array() expects exactly 1 parameter, 2 given (D:\WWW\yvvy\protected\modules\admin\components\Controller.php:25)
Stack trace:
#0 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#1 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#2 D:\WWW\yvvy\yii\web\CController.php(265): CatalogueController->runActionWithFilters()
#3 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CatalogueController->run()
#4 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#6 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/admin/catalogue/index
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (25)
in D:\WWW\yvvy\index.php (15)
2015/09/17 13:13:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "contact.htmlsaas".' in D:\WWW\yvvy\yii\web\CController.php:483
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(270): CController->missingAction('contact.htmlsaa...')
#1 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('contact.htmlsaa...')
#2 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('site/contact.ht...')
#3 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\WWW\yvvy\index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/site/contact.htmlsaas
---
2015/09/17 13:15:17 [error] [php] include(Yiii.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (D:\WWW\yvvy\yii\YiiBase.php:432)
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): spl_autoload_call()
#1 D:\WWW\yvvy\yii\web\CBaseController.php(126): require()
#2 D:\WWW\yvvy\yii\web\CBaseController.php(95): CatalogueController->renderInternal()
#3 D:\WWW\yvvy\yii\web\CController.php(784): CatalogueController->renderFile()
#4 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CatalogueController->render()
#5 unknown(0): CatalogueController->actionIndex()
#6 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs()
#7 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#8 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams()
#9 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CatalogueController->runAction()
#10 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(35): CFilterChain->run()
#11 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): CatalogueController->filterAccessAuth()
#12 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#13 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#14 D:\WWW\yvvy\yii\web\CController.php(265): CatalogueController->runActionWithFilters()
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CatalogueController->run()
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#17 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#18 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/admin/catalogue/index
in D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php (113)
in D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php (9)
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (35)
in D:\WWW\yvvy\index.php (15)
2015/09/17 13:16:30 [error] [php] include(Yiii.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (D:\WWW\yvvy\yii\YiiBase.php:432)
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): spl_autoload_call()
#1 D:\WWW\yvvy\yii\web\CBaseController.php(126): require()
#2 D:\WWW\yvvy\yii\web\CBaseController.php(95): CatalogueController->renderInternal()
#3 D:\WWW\yvvy\yii\web\CController.php(784): CatalogueController->renderFile()
#4 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CatalogueController->render()
#5 unknown(0): CatalogueController->actionIndex()
#6 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs()
#7 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#8 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams()
#9 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CatalogueController->runAction()
#10 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(35): CFilterChain->run()
#11 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): CatalogueController->filterAccessAuth()
#12 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#13 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#14 D:\WWW\yvvy\yii\web\CController.php(265): CatalogueController->runActionWithFilters()
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CatalogueController->run()
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#17 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#18 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/admin/catalogue/index
in D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php (113)
in D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php (9)
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (35)
in D:\WWW\yvvy\index.php (15)
2015/09/17 13:16:31 [error] [php] include(Yiii.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (D:\WWW\yvvy\yii\YiiBase.php:432)
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): spl_autoload_call()
#1 D:\WWW\yvvy\yii\web\CBaseController.php(126): require()
#2 D:\WWW\yvvy\yii\web\CBaseController.php(95): CatalogueController->renderInternal()
#3 D:\WWW\yvvy\yii\web\CController.php(784): CatalogueController->renderFile()
#4 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CatalogueController->render()
#5 unknown(0): CatalogueController->actionIndex()
#6 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs()
#7 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#8 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams()
#9 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CatalogueController->runAction()
#10 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(35): CFilterChain->run()
#11 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): CatalogueController->filterAccessAuth()
#12 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#13 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#14 D:\WWW\yvvy\yii\web\CController.php(265): CatalogueController->runActionWithFilters()
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CatalogueController->run()
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#17 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#18 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/admin/catalogue/index
in D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php (113)
in D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php (9)
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (35)
in D:\WWW\yvvy\index.php (15)
2015/09/17 13:16:39 [error] [php] include(Yiii.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (D:\WWW\yvvy\yii\YiiBase.php:432)
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): spl_autoload_call()
#1 D:\WWW\yvvy\yii\web\CBaseController.php(126): require()
#2 D:\WWW\yvvy\yii\web\CBaseController.php(95): CatalogueController->renderInternal()
#3 D:\WWW\yvvy\yii\web\CController.php(784): CatalogueController->renderFile()
#4 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CatalogueController->render()
#5 unknown(0): CatalogueController->actionIndex()
#6 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs()
#7 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#8 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams()
#9 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CatalogueController->runAction()
#10 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(35): CFilterChain->run()
#11 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): CatalogueController->filterAccessAuth()
#12 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#13 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#14 D:\WWW\yvvy\yii\web\CController.php(265): CatalogueController->runActionWithFilters()
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CatalogueController->run()
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#17 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#18 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/admin/catalogue/index
in D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php (113)
in D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php (9)
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (35)
in D:\WWW\yvvy\index.php (15)
2015/09/17 13:16:40 [error] [php] include(Yiii.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (D:\WWW\yvvy\yii\YiiBase.php:432)
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): spl_autoload_call()
#1 D:\WWW\yvvy\yii\web\CBaseController.php(126): require()
#2 D:\WWW\yvvy\yii\web\CBaseController.php(95): CatalogueController->renderInternal()
#3 D:\WWW\yvvy\yii\web\CController.php(784): CatalogueController->renderFile()
#4 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CatalogueController->render()
#5 unknown(0): CatalogueController->actionIndex()
#6 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs()
#7 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#8 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams()
#9 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CatalogueController->runAction()
#10 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(35): CFilterChain->run()
#11 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): CatalogueController->filterAccessAuth()
#12 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#13 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#14 D:\WWW\yvvy\yii\web\CController.php(265): CatalogueController->runActionWithFilters()
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CatalogueController->run()
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController()
#17 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#18 D:\WWW\yvvy\index.php(15): CWebApplication->run()
REQUEST_URI=/admin/catalogue/index
in D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php (113)
in D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php (9)
in D:\WWW\yvvy\protected\modules\admin\components\Controller.php (35)
in D:\WWW\yvvy\index.php (15)
2015/09/17 13:18:03 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.user_name" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('user_name')
#1 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): CWebUser->__get('user_name')
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(784): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CController->render('index', Array)
#6 [internal function]: CatalogueController->actionIndex(0)
#7 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(CatalogueController), Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(CatalogueController), Object(ReflectionMethod), Array)
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(35): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/admin/catalogue/index
HTTP_REFERER=http://yvvy.mom.com/admin/index/login
---
2015/09/17 13:18:04 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.user_name" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('user_name')
#1 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): CWebUser->__get('user_name')
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(784): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CController->render('index', Array)
#6 [internal function]: CatalogueController->actionIndex(0)
#7 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(CatalogueController), Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(CatalogueController), Object(ReflectionMethod), Array)
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(35): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/admin/catalogue/index
HTTP_REFERER=http://yvvy.mom.com/admin/index/login
---
2015/09/17 13:20:03 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.username" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('username')
#1 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): CWebUser->__get('username')
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(784): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CController->render('index', Array)
#6 [internal function]: CatalogueController->actionIndex(0)
#7 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(CatalogueController), Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(CatalogueController), Object(ReflectionMethod), Array)
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(35): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/admin/catalogue/index
HTTP_REFERER=http://yvvy.mom.com/admin/index/login
---
2015/09/17 13:20:04 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.username" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('username')
#1 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): CWebUser->__get('username')
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(784): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CController->render('index', Array)
#6 [internal function]: CatalogueController->actionIndex(0)
#7 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(CatalogueController), Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(CatalogueController), Object(ReflectionMethod), Array)
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(35): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/admin/catalogue/index
HTTP_REFERER=http://yvvy.mom.com/admin/index/login
---
2015/09/17 13:20:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 13:20:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 13:21:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 13:21:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 13:32:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 13:33:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 13:34:04 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.user" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('user')
#1 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): CWebUser->__get('user')
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(784): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CController->render('index', Array)
#6 [internal function]: CatalogueController->actionIndex(0)
#7 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(CatalogueController), Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(CatalogueController), Object(ReflectionMethod), Array)
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(35): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/admin/catalogue/index
HTTP_REFERER=http://yvvy.mom.com/admin/index/login
---
2015/09/17 13:35:49 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.username" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('username')
#1 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): CWebUser->__get('username')
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(784): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CController->render('index', Array)
#6 [internal function]: CatalogueController->actionIndex(0)
#7 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(CatalogueController), Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(CatalogueController), Object(ReflectionMethod), Array)
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(35): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/admin/catalogue/index
HTTP_REFERER=http://yvvy.mom.com/admin/index/login
---
2015/09/17 13:36:23 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.username" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('username')
#1 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): CWebUser->__get('username')
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(784): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CController->render('index', Array)
#6 [internal function]: CatalogueController->actionIndex(0)
#7 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(CatalogueController), Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(CatalogueController), Object(ReflectionMethod), Array)
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(35): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/admin/catalogue/index
HTTP_REFERER=http://yvvy.mom.com/admin/index/login
---
2015/09/17 13:40:18 [error] [exception.CException] exception 'CException' with message 'UserIdentity and its behaviors do not have a method or closure named "setUser".' in D:\WWW\yvvy\yii\base\CComponent.php:266
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\components\UserIdentity.php(38): CComponent->__call('setUser', Array)
#1 D:\WWW\yvvy\protected\modules\admin\components\UserIdentity.php(38): UserIdentity->setUser(Object(User))
#2 D:\WWW\yvvy\protected\modules\admin\models\LoginForm.php(54): UserIdentity->authenticate()
#3 D:\WWW\yvvy\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 D:\WWW\yvvy\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 D:\WWW\yvvy\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(27): CModel->validate()
#7 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionLogin()
#8 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#10 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(29): CFilterChain->run()
#11 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#12 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#14 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#17 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#18 D:\WWW\yvvy\index.php(15): CApplication->run()
#19 {main}
REQUEST_URI=/admin/index/login
HTTP_REFERER=http://yvvy.mom.com/admin/index/login
---
2015/09/17 13:41:11 [error] [exception.CException] exception 'CException' with message 'UserIdentity and its behaviors do not have a method or closure named "setUser".' in D:\WWW\yvvy\yii\base\CComponent.php:266
Stack trace:
#0 D:\WWW\yvvy\protected\modules\admin\components\UserIdentity.php(38): CComponent->__call('setUser', Array)
#1 D:\WWW\yvvy\protected\modules\admin\components\UserIdentity.php(38): UserIdentity->setUser(Object(User))
#2 D:\WWW\yvvy\protected\modules\admin\models\LoginForm.php(54): UserIdentity->authenticate()
#3 D:\WWW\yvvy\yii\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 D:\WWW\yvvy\yii\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 D:\WWW\yvvy\yii\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(27): CModel->validate()
#7 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionLogin()
#8 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#10 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(29): CFilterChain->run()
#11 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#12 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#14 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/log...')
#17 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#18 D:\WWW\yvvy\index.php(15): CApplication->run()
#19 {main}
REQUEST_URI=/admin/index/login
HTTP_REFERER=http://yvvy.mom.com/admin/index/login
---
2015/09/17 13:46:32 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.username" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('username')
#1 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): CWebUser->__get('username')
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(784): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CController->render('index', Array)
#6 [internal function]: CatalogueController->actionIndex(0)
#7 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(CatalogueController), Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(CatalogueController), Object(ReflectionMethod), Array)
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(36): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/admin/catalogue/index
HTTP_REFERER=http://yvvy.mom.com/admin/index/login
---
2015/09/17 13:46:40 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.user_name" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('user_name')
#1 D:\WWW\yvvy\protected\modules\admin\views\layouts\template.php(113): CWebUser->__get('user_name')
#2 D:\WWW\yvvy\yii\web\CBaseController.php(126): require('D:\WWW\yvvy\pro...')
#3 D:\WWW\yvvy\yii\web\CBaseController.php(95): CBaseController->renderInternal('D:\WWW\yvvy\pro...', Array, true)
#4 D:\WWW\yvvy\yii\web\CController.php(784): CBaseController->renderFile('D:\WWW\yvvy\pro...', Array, true)
#5 D:\WWW\yvvy\protected\modules\admin\controllers\catalogueController.php(9): CController->render('index', Array)
#6 [internal function]: CatalogueController->actionIndex(0)
#7 D:\WWW\yvvy\yii\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(CatalogueController), Array)
#8 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(CatalogueController), Object(ReflectionMethod), Array)
#9 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(36): CFilterChain->run()
#12 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#13 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#14 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#15 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#17 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#18 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#19 D:\WWW\yvvy\index.php(15): CApplication->run()
#20 {main}
REQUEST_URI=/admin/catalogue/index
HTTP_REFERER=http://yvvy.mom.com/admin/index/login
---
2015/09/17 13:52:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 13:53:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 13:54:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "extra_search".' in D:\WWW\yvvy\yii\web\CController.php:483
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(270): CController->missingAction('extra_search')
#1 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('extra_search')
#2 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#3 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\WWW\yvvy\index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/admin/catalogue/extra_search.html
HTTP_REFERER=http://yvvy.mom.com/admin/catalogue/index
---
2015/09/17 13:56:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 13:57:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 14:19:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "banner_id".' in D:\WWW\yvvy\yii\web\CController.php:483
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(270): CController->missingAction('banner_id')
#1 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('banner_id')
#2 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/banner/ba...')
#3 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\WWW\yvvy\index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/admin/banner/banner_id/4.html
HTTP_REFERER=http://yvvy.mom.com/admin/banner.html
---
2015/09/17 14:26:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 14:32:41 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser._userId" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('_userId')
#1 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(12): CWebUser->__get('_userId')
#2 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionIndex()
#3 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(36): CFilterChain->run()
#6 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#7 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#9 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/ind...')
#12 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#13 D:\WWW\yvvy\index.php(15): CApplication->run()
#14 {main}
REQUEST_URI=/admin/index/index
---
2015/09/17 14:32:42 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser._userId" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('_userId')
#1 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(12): CWebUser->__get('_userId')
#2 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionIndex()
#3 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(36): CFilterChain->run()
#6 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#7 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#9 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/ind...')
#12 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#13 D:\WWW\yvvy\index.php(15): CApplication->run()
#14 {main}
REQUEST_URI=/admin/index/index
---
2015/09/17 14:32:51 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.userid" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('userid')
#1 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(12): CWebUser->__get('userid')
#2 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionIndex()
#3 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(36): CFilterChain->run()
#6 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#7 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#9 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/ind...')
#12 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#13 D:\WWW\yvvy\index.php(15): CApplication->run()
#14 {main}
REQUEST_URI=/admin/index/index
---
2015/09/17 14:32:56 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.userId" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('userId')
#1 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(12): CWebUser->__get('userId')
#2 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionIndex()
#3 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(36): CFilterChain->run()
#6 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#7 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#9 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/ind...')
#12 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#13 D:\WWW\yvvy\index.php(15): CApplication->run()
#14 {main}
REQUEST_URI=/admin/index/index
---
2015/09/17 14:32:57 [error] [exception.CException] exception 'CException' with message 'Property "CWebUser.userId" is not defined.' in D:\WWW\yvvy\yii\base\CComponent.php:130
Stack trace:
#0 D:\WWW\yvvy\yii\web\auth\CWebUser.php(146): CComponent->__get('userId')
#1 D:\WWW\yvvy\protected\modules\admin\controllers\IndexController.php(12): CWebUser->__get('userId')
#2 D:\WWW\yvvy\yii\web\actions\CInlineAction.php(49): IndexController->actionIndex()
#3 D:\WWW\yvvy\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\WWW\yvvy\protected\modules\admin\components\Controller.php(36): CFilterChain->run()
#6 D:\WWW\yvvy\yii\web\filters\CInlineFilter.php(58): Controller->filterAccessAuth(Object(CFilterChain))
#7 D:\WWW\yvvy\yii\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 D:\WWW\yvvy\yii\web\CController.php(291): CFilterChain->run()
#9 D:\WWW\yvvy\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('index')
#11 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/index/ind...')
#12 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#13 D:\WWW\yvvy\index.php(15): CApplication->run()
#14 {main}
REQUEST_URI=/admin/index/index
---
2015/09/17 14:36:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in D:\WWW\yvvy\yii\web\CController.php:483
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(270): CController->missingAction('login')
#1 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#2 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#3 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\WWW\yvvy\index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/admin/catalogue/login.html
HTTP_REFERER=http://yvvy.mom.com/admin/catalogue/index
---
2015/09/17 14:36:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in D:\WWW\yvvy\yii\web\CController.php:483
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(270): CController->missingAction('login')
#1 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#2 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#3 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\WWW\yvvy\index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/admin/catalogue/login.html
HTTP_REFERER=http://yvvy.mom.com/admin/catalogue/index
---
2015/09/17 14:37:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in D:\WWW\yvvy\yii\web\CController.php:483
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(270): CController->missingAction('login')
#1 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#2 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#3 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\WWW\yvvy\index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/admin/catalogue/login.html
HTTP_REFERER=http://yvvy.mom.com/admin/catalogue/index
---
2015/09/17 14:37:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in D:\WWW\yvvy\yii\web\CController.php:483
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(270): CController->missingAction('login')
#1 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#2 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#3 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\WWW\yvvy\index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/admin/catalogue/login.html
HTTP_REFERER=http://yvvy.mom.com/admin/catalogue/index
---
2015/09/17 14:37:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in D:\WWW\yvvy\yii\web\CController.php:483
Stack trace:
#0 D:\WWW\yvvy\yii\web\CController.php(270): CController->missingAction('login')
#1 D:\WWW\yvvy\yii\web\CWebApplication.php(282): CController->run('login')
#2 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/catalogue...')
#3 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#4 D:\WWW\yvvy\index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/admin/catalogue/login.html
HTTP_REFERER=http://yvvy.mom.com/admin/catalogue/index
---
2015/09/17 14:40:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 14:40:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 14:40:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 14:41:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 14:42:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
2015/09/17 14:42:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin/js/jquery-1.10.1.min.map".' in D:\WWW\yvvy\yii\web\CWebApplication.php:286
Stack trace:
#0 D:\WWW\yvvy\yii\web\CWebApplication.php(141): CWebApplication->runController('admin/js/jquery...')
#1 D:\WWW\yvvy\yii\base\CApplication.php(184): CWebApplication->processRequest()
#2 D:\WWW\yvvy\index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/admin/js/jquery-1.10.1.min.map
---
